### ISSUE TITLE
Loading but not working

### ISSUE THREAD

**Issue by Sheepiely** [coderpussy/MMM-Mopidy-MPD#1]
Hi,

I have followed your instructions in Readme and installed MMM-Mopidy-MPD but when I run my Magic Mirror, your module is just constantly loading although the Mopidy server is running and I'm playing music on it. I also can't seem to see an error in the Magic Mirror log.

My config file:
{
		module: "MMM-Mopidy-MPD",
		position: "bottom_left",	// This can be any of the regions.
		config: {
			// See 'Configuration options' for more information.
			hostname: "192.168.x.xx",
			port: 66xx
		}
	},

Hostname and port match the url which I use to access Iris.

@coderpussy Are you able to help me to troubleshoot?

**Comment by coderpussy** [comment]
@Sheepiely Hi, i will try to help you. :-)
I'm just guessing, but did you the setting on MagicMirror to allow connections not only from localhost (e.g. 0.0.0.0)?

**Comment by Sheepiely** [comment]
when I run sudo mopidyctl config

[http]
enabled = true
hostname = 0.0.0.0
port = 6680
zeroconf = Mopidy HTTP server on $hostname
allowed_origins =
csrf_protection = true
default_app = mopidy

**Comment by coderpussy** [comment]
I will take a closer look later. It is some time ago that i created this module. Maybe something changed during this time on MagicMirror and i don't know about. My MagicMirror isn't running for a couple of time.

**Comment by Sheepiely** [comment]
Thanks for looking into it, much appreciated.

**Comment by coderpussy** [comment]
Hi, you tried to use the mopidy mpd port instead of mopidy http port?

Because you said above you use the hostname and port match the url which you use to access Iris. But this port is by default 6680. Mpd have the port 6600 by default.

**Comment by Sheepiely** [comment]
If I use 'localhost' or '192.168.x.xx' as my local host and '6600' as the port. I get the following error:

[04.08.2021 10:03.32.471] [INFO]  Checking git for module: MMM-Mopidy-MPD
[04.08.2021 10:03.32.671] [ERROR] Whoops! There was an uncaught exception...
[04.08.2021 10:03.32.692] [ERROR] Error: connect ECONNREFUSED 127.0.0.1:6600
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6600
}

Is there something I need to configure on the Mopidy side?

**Comment by Sheepiely** [comment]
My [mpd] config:

enabled = true
hostname = 0.0.0.0
port = 6600
password = 
max_connections = 20
connection_timeout = 60
zeroconf = Mopidy MPD server on $hostname
command_blacklist = 
  listall
  listallinfo
default_playlist_scheme = m3u

**Comment by Sheepiely** [comment]
Ok, I've figured out what it is, in the mpd config, "hostname = ::" needs to be used and it's all working now.

Thanks!
